name: mandadero
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1
  google_fonts: ^1.0.0
  provider: ^4.0.5+1

  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  flutter_facebook_login: ^3.0.0
  firebase_storage: ^3.1.6
  google_sign_in: ^4.4.6
  google_maps_flutter: ^0.5.28+1
  meta: ^1.1.6
  shared_preferences: ^0.5.7+2
  cloud_firestore: ^0.13.5
  geolocator: ^5.3.2+2

  #awesome_card: ^1.1.0
  flutter_credit_card: ^0.1.3
  #cached_network_image: ^2.2.0+1
  
  stripe_payment: ^1.0.7

  http: ^0.12.1
  progress_dialog: ^1.2.2
  image_picker: ^0.6.0+17
  image_downloader: ^0.19.2
  flutter_rating_bar: ^3.0.1+1
  
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - lib/assets/
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
